services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: focalboard
    depends_on:
      - focalboard-db
    ports:
      - 8000:8000
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
    volumes:
      - "./config.json:/opt/focalboard/config.json"
      - ./fbdata:/opt/focalboard/data
    restart: always
    networks:
      - default

  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password

volumes:
  fbdata:
  pgdata:


